name: demo

on:
  push:
    branches: [ master ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
          check-latest: true
      - name: Build all examples 🛠️
        run: |
          npm install
          npm install --prefix examples/minimal
          npm run build --prefix examples/minimal
          npm install --prefix examples/simple
          npm run build --prefix examples/simple
          npm install --prefix examples/multiple
          npm run build --prefix examples/multiple
          npm install --prefix examples/advanced
          npm run build --prefix examples/advanced
          rm -rf examples/minimal/node_modules examples/minimal/package-lock.json
          rm -rf examples/simple/node_modules examples/simple/package-lock.json
          rm -rf examples/multiple/node_modules examples/multiple/package-lock.json
          rm -rf examples/advanced/node_modules examples/advanced/package-lock.json
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: demo
          folder: examples
