name: demo

on:
  push:
    branches: [ master ]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '16'
          check-latest: true
      - name: Build demo 🛠️
        run: |
          npm install
          npm install --prefix demo/minimal
          npm run build --prefix demo/minimal
          npm install --prefix demo/simple
          npm run build --prefix demo/simple
          npm install --prefix demo/multiple
          npm run build --prefix demo/multiple
          npm install --prefix demo/advanced
          npm run build --prefix demo/advanced
          rm -rf demo/minimal/node_modules demo/minimal/package-lock.json
          rm -rf demo/simple/node_modules demo/simple/package-lock.json
          rm -rf demo/multiple/node_modules demo/multiple/package-lock.json
          rm -rf demo/advanced/node_modules demo/advanced/package-lock.json
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: demo
          folder: demo
          clean: false
